DROP DATABASE IF EXISTS include;
CREATE DATABASE IF NOT EXISTS include;
USE include;

CREATE TABLE IF NOT EXISTS notas(
    id_nota INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    descricao VARCHAR(100) NOT NULL,
    valor_monetario DECIMAL(10, 2) NOT NULL,
    tipo BOOLEAN NOT NULL,
    PRIMARY KEY (idNota)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;